<a href="https://colab.research.google.com/github/thaiantl-code/hocsau/blob/main/linearregression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
# Linear Regression Project
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt

df = pd.read_csv("https://raw.githubusercontent.com/thaiantl-code/hocsau/refs/heads/main/Advertising.csv")
df = df.drop("Unnamed: 0", axis=1)#dataset co cột unmate là cột dữ liệu không phải feature nên xóa đi

df.corr()# xác định tương quan giữa các cột để xác định feature--> chọn TV và radio

                 TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.782224
Radio      0.054809  1.000000   0.354104  0.576223
Newspaper  0.056648  0.354104   1.000000  0.228299
Sales      0.782224  0.576223   0.228299  1.000000

In [ ]:
df.head()

In [ ]:
df.duplicated().sum() # kiem tra co duplicated khong

In [ ]:
df.isnull().values.any()# kiem tra co missing ko

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.heatmap(df.corr(), annot=True, cmap="coolwarm")
plt.show()

In [ ]:
import seaborn as sns
sns.boxplot(y='TV', x='Sales', data = df)

In [ ]:
#xac dinh outlier và loai bỏ
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)

IQR = Q3 - Q1

outliers = df[
    ((df < (Q1 - 1.5 * IQR)) | (df > (Q3 + 1.5 * IQR)))
]

print(outliers)

In [ ]:
#loai bo oulier
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)

IQR = Q3 - Q1

data_clean = df[
    ~((df < (Q1 - 1.5 * IQR)) |
      (df > (Q3 + 1.5 * IQR))).any(axis=1)
]

In [ ]:
sns.pairplot(df)

In [ ]:
import matplotlib.pyplot as plt

plt.scatter(df["TV"], df["Sales"])
plt.xlabel("TV")
plt.ylabel("Sales")
plt.show()

In [22]:
import pandas as pd


# 2. Chọn feature và target
X = df[['TV', 'Radio']]
y = df['Sales']

# 3. Train / Test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 4. Tạo pipeline
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.linear_model import LinearRegression

model = Pipeline([
    ("poly", PolynomialFeatures(degree=2)),
    ("scaler", StandardScaler()),
    ("linear", LinearRegression())
])

# 5. Train model
model.fit(X_train, y_train)

# 6. Predict
y_pred = model.predict(X_test)

In [23]:
# TODO: Make predictions
y_pred = model.predict(X_test)
import pandas as pd

pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred
}).head()

     Actual  Predicted
95     16.9  17.164348
15     22.4  22.681214
30     21.4  20.497162
158     7.3   7.464108
128    24.7  24.449519

In [24]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'MSE: {mse}')
print(f'R2 Score: {r2}')

MSE: 0.3641558727915572
R2 Score: 0.9884627879931588

In [25]:
new_data = [[100, 20]]  # TV, Radio

pred = model.predict(new_data)
print("Predicted Sales:", pred[0])

Predicted Sales: 11.941645461416634

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(